name: Simple Python Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x' # Use the desired Python version here
    - name: Run Python script
      run: python main.py # Replace 'helloworld.py' with the name of your Python script
